2019-10-05 18:23:44 WARNING (zeroconf-Engine) [zeroconf] Choked at offset 0 while unpacking b'\n\xba\x10\x00'
2019-10-05 18:23:44 WARNING (zeroconf-Engine) [zeroconf] Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 664, in __init__
    self.read_header()
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 687, in read_header
    ) = self.unpack(b'!6H')
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 674, in unpack
    info = struct.unpack(format_, self.data[self.offset : self.offset + length])
struct.error: unpack requires a buffer of 12 bytes
2019-10-06 13:40:25 WARNING (SyncWorker_13) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-06 13:58:30 WARNING (SyncWorker_14) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-08 20:10:21 WARNING (SyncWorker_10) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-08 20:12:56 WARNING (SyncWorker_18) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-08 20:21:12 WARNING (SyncWorker_14) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-08 23:48:19 WARNING (SyncWorker_17) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-08 23:51:56 WARNING (SyncWorker_15) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-09 08:36:06 WARNING (SyncWorker_4) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-09 08:40:45 WARNING (SyncWorker_0) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-09 08:47:59 WARNING (SyncWorker_8) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-09 16:43:44 WARNING (SyncWorker_3) [homeassistant.components.tplink.light] Could not read state for 10.0.0.75: Communication error
2019-10-10 20:35:31 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2019-10-10 20:35:31 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2019-10-10 20:35:46 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
2019-10-10 20:51:27 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
